version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run:
          name: Build
          command: mvn -B -DskipTests -s .circleci.settings.xml clean package
      - run:
          name: Test
          command: mvn -s .circleci.settings.xml test

workflows:
  ci: 
    jobs:
      - build-and-test
