version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run:
          name: Build with Maven
          command: mvn -B -DskipTests clean package
      - run:
          name: Run Unit Tests
          command: mvn test
  scan-with-sonarcloud:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run:
          name: Run Jacoco Plugin for Test Coverage
          command: mvn package
      - run:
          name: Analyze on SonarCloud
          command: mvn verify sonar:sonar -Dsonar.projectKey=LeelaChacha_odin

workflows:
  ci: 
    jobs:
      - build-and-test
      - scan-with-sonarcloud:
          context: SonarCloud
